version: '3'
services:
  db:
    container_name: 'postgres_db'
    image: postgres:9.6
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - szzti-db:/var/lib/postgresql/data

  backend:
    image: wheeezyx/szzti-backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  szzti-db:
    external: false